## Plugin configuration for the KBase UI
---
plugins:
    # Plugins which come-with kbase-ui
    -
        mainwindow
    -
        message
    -
        welcome
    -
        login
    -
        userprofile
    -
        datasearch
    -
        narrativemanager
    -
        narrativestore 
    # external:
    -
        name: viswidgets
        bower:
            name: kbase-ui-plugin-vis-widgets
            version: eapearson/kbase-ui-plugin-vis-widgets#master
        copy:
            path: src/plugin
    -
        name: typeview
        bower:
            name: kbase-ui-plugin-typeview
            version: eapearson/kbase-ui-plugin-typeview#master
        copy:
            path: src/plugin
    -
        name: dataview
        bower:
            name: kbase-ui-plugin-dataview
            version: eapearson/kbase-ui-plugin-dataview#master
        copy:
            path: src/plugin
    -
        name: dashboard
        bower:
            name: kbase-ui-plugin-dashboard
            version: eapearson/kbase-ui-plugin-dashboard#master
        copy:
            path: src/plugin      
    -
        name: databrowser
        bower:
            name: kbase-ui-plugin-databrowser
            version: eapearson/kbase-ui-plugin-databrowser#master
        copy:
            path: src/plugin
    -
        name: typebrowser
        bower:
            name: kbase-ui-plugin-typebrowser
            version: eapearson/kbase-ui-plugin-typebrowser#master
        copy:
            path: src/plugin
    -
        name: datawidgets
        bower:
            name: kbase-ui-plugin-datawidgets
            version: eapearson/kbase-ui-plugin-datawidgets
        copy:
            path: src/plugin