#!/usr/bin/env bash

# source "${DIR}/scripts/host/create-dev-proxy-env-vars.bash"
source "${DIR}/.devcontainer/proxy.env"

set -e 
echo "Render development proxy config files"
echo "Parameters (Environment Variables):"
echo ""
echo "UI_DOMAIN = ${UI_DOMAIN}"
echo "KBASE_UI_DOMAIN = ${KBASE_UI_DOMAIN}"
echo ""



# Generate the deployment configs that are normally generated by the entrypoint in the
# Dockerfile. Note that for development we don't actually use nginx.conf, but we
# generate it here so we can inspect it.
    # --env-file ${DIR}/.devcontainer/proxy.env \
docker compose \
    -f ${DIR}/tools/dockerize/docker-compose.yml \
    run \
    --rm \
    dockerize \
    -template /app/tools/proxy/contents/conf/nginx.conf.tmpl:/app/build/deploy/proxy-nginx.conf

