menus:
    authenticated: 
        main: [narrative, appcatalog, search, dashboard, bulk-ui]
        developer: []
        help: [contact-kbase, about-kbase, help]
    unauthenticated: 
        main: [appcatalog, search]
        developer: []
        help: [contact-kbase, about-kbase, help]
