version: '3.6'
services:
    dockerize:
        working_dir: /app
        image: powerman/dockerize
        container_name: dockerize
        dns: 8.8.8.8
        env_file:
          - $ENV_FILE
          # - ../../dev/templates-context.env
        volumes:
            - $DIR:/app