## Plugin configuration for the KBase UI
---
plugins:
    # Plugins which come-with kbase-ui
    -
        mainwindow
    -
        message
    -
        welcome
    -
        login
    -
        userprofile
    -
        datasearch
    -
        narrativemanager
    -
        narrativestore 
    # external:
    -   
        # Becomes the plugin directory name
        name: viswidgetdemo
        # Installation configuration.
        # Provided to bower. The package is fed to 
        # bower install <package>  
        # and
        # bower update <package>
        bower: 
            name: kbase-ui-plugin-demo-vis-widget
            version: eapearson/kbase-ui-plugin-demo-vis-widget#master
        # This defaults to dist/plugin. If this is not the case, then
        # set it here. This is for the grunt task which copies the 
        # package, as installed by bower.
        # The grunt "bowerCopy" tasks needs the bower package name, in order to locate
        # the source, the plugin name, to create the destination in plugins,
        # and the path within the packge to the plugin source, which is 
        # standardized to dist/plugin but can be overridden by the cwd (named
        # to match the grunt usage of cwd to indicate the base directory for 
        # a task operation on files.)            
        copy:
            # only required if the code is not located in dist/plugin
            path: src/plugin
    -
        name: viswidgets
        bower:
            name: kbase-ui-plugin-vis-widgets
            version: eapearson/kbase-ui-plugin-vis-widgets#master
        copy:
            path: src/plugin
    -
        name: typeview
        bower:
            name: kbase-ui-plugin-typeview
            version: eapearson/kbase-ui-plugin-typeview#master
        copy:
            path: src/plugin
    -
        name: dataview
        bower:
            name: kbase-ui-plugin-dataview
            version: eapearson/kbase-ui-plugin-dataview#master
        copy:
            path: src/plugin
    -
        name: dashboard
        bower:
            name: kbase-ui-plugin-dashboard
            version: eapearson/kbase-ui-plugin-dashboard#master
        copy:
            path: src/plugin      
    -
        name: databrowser
        bower:
            name: kbase-ui-plugin-databrowser
            version: eapearson/kbase-ui-plugin-databrowser#master
        copy:
            path: src/plugin
    -
        name: typebrowser
        bower:
            name: kbase-ui-plugin-typebrowser
            version: eapearson/kbase-ui-plugin-typebrowser#master
        copy:
            path: src/plugin
    -
        name: datawidgets
        bower:
             name: kbase-ui-plugin-datawidgets
             version: eapearson/kbase-ui-plugin-datawidgets#master
        # The link install method will create a soft link in the plugin
        # dir to source/path
        #link:
        #    source: ../kbase-ui-plugin-datawidgets
        copy:
            path: src/plugin