# Deploy-Time Config for Auth2 Local Development
---
deploy:
  environment: ci
  hostname: ci.kbase.us
  icon: flask
  name: Continuous Integration
  services:
    urlBase: https://ci.kbase.us
ui:
  services:
    analytics:
      google:
        hostname: ci.kbase.us
        code: UA-74532036-1
  features:
    auth:
      selected: auth2

