version: '3.6'
services:
    deno:
        build:
            # context needs to be the entire repo,  because we need to
            # volume mount into the build directory
            context: ../..
            dockerfile: tools/deno-cli/Dockerfile
        image: kbase/deno:dev
        container_name: kbase-deno
        dns: 8.8.8.8
        volumes:
            - $DIR:/app
