version: '3.6'
services:
    node:
        working_dir: /app
        build:
          context: .
          dockerfile: Dockerfile
        container_name: node-builder
        dns: 8.8.8.8
        volumes:
            - $DIR:/app