---
name: PR to main3 opened
on:
  pull_request:
    branches:
      - main3
    types:
      - opened
      - reopened
      - synchronize
jobs:
  test:
    uses: ./.github/workflows/reusable_test.yml
  build-push:
    needs: test
    uses: ./.github/workflows/reusable_build-push.yml
    with:
      name: '${{ github.event.repository.name }}'
      tags: pr${{ github.event.number }}
    secrets: inherit
