---
name: PR To main (or master) merged
on:
  pull_request:
    branches:
      - main
      - master
    types:
      - closed
jobs:
  test:
    if: ${{ github.event.pull_request.merged }}
    uses: ./.github/workflows/reusable_test.yml
  build-push:
    if: ${{ github.event.pull_request.merged }}
    needs: test
    uses: ./.github/workflows/reusable_build-push.yml
    with:
      name: '${{ github.event.repository.name }}'
      tags: latest-rc
      buildConfig: ci
    secrets: inherit
