---
name: Ensure release tag is semantic version
on:
  workflow_call:
    inputs:
      release_tag:
        required: true
        type: string
jobs:
  ensure-semver:
    runs-on: ubuntu-latest
    steps:
      - name: Validate that release tag as a proper semantic version prefixed with a v
        uses: actions/github-script@v6
        with:
          script: |
            const releaseTag = '${{ inputs.release_tag }}';
            if (!/v^[0-9]+\.[0-9]+\.[0-9]+$/.test(releaseTag)) {
              core.setFailed(`Release version must follow semantic version naming prefixed with a "v" (e.g. v1.2.3) but is "${releaseTag}"`)
            }
